### PR TITLE
Removed deprecated Twig features

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by BenjaminPaap** [comment]
:+1: for this one to be merged

**Comment by XWB** [comment]
Ping @schmittjoh

**Comment by Comrade42** [comment]
:+1: Need this in production ASAP

**Comment by gaydarov** [comment]
+1

**Comment by Ener-Getick** [comment]
closed in favor of https://github.com/schmittjoh/JMSSecurityExtraBundle/pull/202

**Pull request closed without merging**
