### PR TITLE
Added a "hasClassPermission" Expression for checking classe scope permissions

### PR DESCRIPTION
**Pull request by benjamindulau**
Usage example:

/**
 * @PreAuthorize("hasClassPermission('Foo\BarBundle\Entity\Album', 'CREATE')")
 */
public function newAction()
{
}

### CODE REVIEW

**Comment by halloverden** [comment]
Hi. I really, really, really need this functionality to complete my authorization. Only thing that remains for me to be able to use this amazing bundle. Any release date on this?

**Comment by andreaslarssen** [comment]
Two years and counting

**Comment by schmittjoh** [comment]
Could someone re-base this on latest master?

**Comment by benjamindulau** [comment]
Done

**Comment by schmittjoh** [comment]
Thanks

**Comment by andreaslarssen** [comment]
Nice! Thanks guys!

**Comment by erichfosse** [comment]
WOHOO!
Thanks a bunch!

**Pull request merged**
